In [4]:
print(123)

123


In [5]:
import numpy as np

In [6]:
list1 = np.arange(7)
list1 = list1.reshape(7,1)

In [11]:
list1

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [12]:
np.max(list1)

6

In [13]:
list1.shape

(7, 1)

In [15]:
list1[[3,3,1]]

array([[3],
       [3],
       [1]])

In [2]:
dick = {
    'black':1,
    'white':2
}

In [3]:
dick

{'black': 1, 'white': 2}

TypeError: unhashable type: 'list'

In [1]:
from utils.utils import normalizeRows, softmax

In [21]:
list2 = np.random.randint(10,size = (3,3))

In [22]:
list2

array([[9, 3, 6],
       [2, 5, 0],
       [9, 1, 0]])

In [16]:
softmax(list2)

array([[1.78679819e-02, 6.57326319e-03, 9.75558755e-01],
       [9.96620823e-01, 2.47037604e-03, 9.08800555e-04],
       [7.05384513e-01, 2.59496460e-01, 3.51190270e-02]])

In [23]:
np.max(list2,axis = 1)

array([9, 5, 9])

In [24]:
np.max(list2)

9

In [25]:
list2

array([[9, 3, 6],
       [2, 5, 0],
       [9, 1, 0]])

In [26]:
list2[2]

array([9, 1, 0])

In [37]:
list2

array([[9, 3, 6],
       [2, 5, 0],
       [9, 1, 0]])

In [29]:
np.sum(list2,axis = 0)

array([20,  9,  6])

In [34]:
list3 = np.random.randint(10,size = (3,))

In [35]:
list3

array([3, 8, 7])

In [36]:
list2 * list3

array([[27, 24, 42],
       [ 6, 40,  0],
       [27,  8,  0]])

In [38]:
3 * list2

array([[27,  9, 18],
       [ 6, 15,  0],
       [27,  3,  0]])